<?php

namespace App\Models;

use App\Enums\ChallengeStatus;
use App\Enums\ChallengeVisibility;
use App\Enums\PeriodType;
use App\Enums\ProofType;
use Carbon\CarbonImmutable;
use Database\Factories\ChallengeFactory;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Scope;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * One shared, fixed timeline that every participant is measured against.
 *
 * @property int $id
 * @property int $creator_id
 * @property string $title
 * @property string|null $description
 * @property string $join_token
 * @property PeriodType $period_type
 * @property int|null $custom_period_days
 * @property CarbonImmutable $starts_at
 * @property int $total_periods
 * @property string $timezone
 * @property ChallengeVisibility $visibility
 * @property ProofType $proof_type
 * @property bool $proof_is_public
 * @property int $default_freezes
 * @property ChallengeStatus $status
 * @property CarbonImmutable|null $announced_at
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property-read User $creator
 * @property-read Collection<int, ChallengePeriod> $periods
 * @property-read Collection<int, ChallengeParticipant> $participants
 */
#[Fillable([
    'creator_id',
    'title',
    'description',
    'join_token',
    'period_type',
    'custom_period_days',
    'starts_at',
    'total_periods',
    'timezone',
    'visibility',
    'proof_type',
    'proof_is_public',
    'default_freezes',
    'status',
    'announced_at',
])]
class Challenge extends Model
{
    /** @use HasFactory<ChallengeFactory> */
    use HasFactory;

    /**
     * What marks a `?start=` payload as a challenge join rather than an invite code.
     */
    public const JOIN_PAYLOAD_PREFIX = 'j_';

    /**
     * @return BelongsTo<User, $this>
     */
    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'creator_id');
    }

    /**
     * The materialised timeline, oldest period first.
     *
     * @return HasMany<ChallengePeriod, $this>
     */
    public function periods(): HasMany
    {
        return $this->hasMany(ChallengePeriod::class)->orderBy('index');
    }

    /**
     * @return HasMany<ChallengeParticipant, $this>
     */
    public function participants(): HasMany
    {
        return $this->hasMany(ChallengeParticipant::class);
    }

    /**
     * Whether one participant's proof may be shown to the others.
     *
     * Two gates, both of which must pass: the creator opted in, and the proof
     * type can honour it at all. A tap has nothing to show, and publishing an
     * autogenerated phrase would hand everyone else the answer.
     */
    public function sharesProofPublicly(): bool
    {
        return $this->proof_is_public && $this->proof_type->supportsPublicProof();
    }

    /**
     * Whether this challenge still needs posting to the announcement channel.
     */
    public function awaitsAnnouncement(): bool
    {
        return $this->visibility->shouldAnnounce() && $this->announced_at === null;
    }

    /**
     * The `?start=` payload that carries this challenge to the bot.
     *
     * Prefixed so `/start` can tell it from an invite code without a database
     * lookup per guess. That works because the two alphabets are disjoint on one
     * character: `MintJoinToken` and `IssueInviteCode` both exclude `_`, so no
     * invite code can ever begin `j_`.
     */
    public function joinPayload(): string
    {
        return self::JOIN_PAYLOAD_PREFIX.$this->join_token;
    }

    /**
     * The deep link that opens the bot on this challenge's join preview.
     *
     * `?start=` rather than `?startapp=`: joining is a bot conversation — it can
     * refuse for want of a slot, and it has to be able to offer the channel gate —
     * and a Mini App cannot be relied on to have been opened at all.
     */
    public function joinLink(): string
    {
        $username = ltrim(config()->string('services.telegram.bot_username'), '@');

        return "https://t.me/{$username}?start={$this->joinPayload()}";
    }

    /**
     * Whether a `?start=` payload is shaped like a challenge join.
     *
     * Distinct from `fromJoinPayload`, which asks whether the payload names a
     * challenge that exists: a dead link is still a join link, and the bot owes
     * "that link is no longer valid" rather than falling through to invite-code
     * attribution and a message about the wrong thing entirely.
     */
    public static function isJoinPayload(?string $payload): bool
    {
        $payload = strtolower(trim((string) $payload));

        return str_starts_with($payload, self::JOIN_PAYLOAD_PREFIX);
    }

    /**
     * The challenge a `?start=` payload names, or null when it names none.
     *
     * Deliberately not filtered by joinability: a closed challenge has to come back
     * so the bot can say it is closed. "This link is not valid" and "that challenge
     * has finished" are different things to hear.
     */
    public static function fromJoinPayload(?string $payload): ?self
    {
        $payload = strtolower(trim((string) $payload));

        if (! str_starts_with($payload, self::JOIN_PAYLOAD_PREFIX)) {
            return null;
        }

        $token = substr($payload, strlen(self::JOIN_PAYLOAD_PREFIX));

        if ($token === '') {
            return null;
        }

        return self::query()->where('join_token', $token)->first();
    }

    /**
     * How many days one period spans, for `period_type = custom` only.
     */
    public function customPeriodDays(): ?int
    {
        return $this->period_type->requiresCustomDays() ? $this->custom_period_days : null;
    }

    /**
     * @param  Builder<$this>  $query
     */
    #[Scope]
    protected function joinable(Builder $query): void
    {
        $query->whereIn('status', [ChallengeStatus::Scheduled, ChallengeStatus::Active]);
    }

    /**
     * @param  Builder<$this>  $query
     */
    #[Scope]
    protected function active(Builder $query): void
    {
        $query->where('status', ChallengeStatus::Active);
    }

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'period_type' => PeriodType::class,
            'custom_period_days' => 'integer',
            'starts_at' => 'datetime',
            'total_periods' => 'integer',
            'visibility' => ChallengeVisibility::class,
            'proof_type' => ProofType::class,
            'proof_is_public' => 'boolean',
            'default_freezes' => 'integer',
            'status' => ChallengeStatus::class,
            'announced_at' => 'datetime',
        ];
    }
}
