<?php

namespace App\Models;

use App\Enums\ChallengeStatus;
use App\Enums\ChallengeVisibility;
use App\Enums\PeriodType;
use App\Enums\ProofType;
use Carbon\CarbonImmutable;
use Database\Factories\ChallengeFactory;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Scope;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * One shared, fixed timeline that every participant is measured against.
 *
 * @property int $id
 * @property int $creator_id
 * @property string $title
 * @property string|null $description
 * @property PeriodType $period_type
 * @property int|null $custom_period_days
 * @property CarbonImmutable $starts_at
 * @property int $total_periods
 * @property string $timezone
 * @property ChallengeVisibility $visibility
 * @property ProofType $proof_type
 * @property bool $proof_is_public
 * @property int $default_freezes
 * @property ChallengeStatus $status
 * @property CarbonImmutable|null $announced_at
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property-read User $creator
 * @property-read Collection<int, ChallengePeriod> $periods
 * @property-read Collection<int, ChallengeParticipant> $participants
 */
#[Fillable([
    'creator_id',
    'title',
    'description',
    'period_type',
    'custom_period_days',
    'starts_at',
    'total_periods',
    'timezone',
    'visibility',
    'proof_type',
    'proof_is_public',
    'default_freezes',
    'status',
    'announced_at',
])]
class Challenge extends Model
{
    /** @use HasFactory<ChallengeFactory> */
    use HasFactory;

    /**
     * @return BelongsTo<User, $this>
     */
    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'creator_id');
    }

    /**
     * The materialised timeline, oldest period first.
     *
     * @return HasMany<ChallengePeriod, $this>
     */
    public function periods(): HasMany
    {
        return $this->hasMany(ChallengePeriod::class)->orderBy('index');
    }

    /**
     * @return HasMany<ChallengeParticipant, $this>
     */
    public function participants(): HasMany
    {
        return $this->hasMany(ChallengeParticipant::class);
    }

    /**
     * Whether one participant's proof may be shown to the others.
     *
     * Two gates, both of which must pass: the creator opted in, and the proof
     * type can honour it at all. A tap has nothing to show, and publishing an
     * autogenerated phrase would hand everyone else the answer.
     */
    public function sharesProofPublicly(): bool
    {
        return $this->proof_is_public && $this->proof_type->supportsPublicProof();
    }

    /**
     * Whether this challenge still needs posting to the announcement channel.
     */
    public function awaitsAnnouncement(): bool
    {
        return $this->visibility->shouldAnnounce() && $this->announced_at === null;
    }

    /**
     * How many days one period spans, for `period_type = custom` only.
     */
    public function customPeriodDays(): ?int
    {
        return $this->period_type->requiresCustomDays() ? $this->custom_period_days : null;
    }

    /**
     * @param  Builder<$this>  $query
     */
    #[Scope]
    protected function joinable(Builder $query): void
    {
        $query->whereIn('status', [ChallengeStatus::Scheduled, ChallengeStatus::Active]);
    }

    /**
     * @param  Builder<$this>  $query
     */
    #[Scope]
    protected function active(Builder $query): void
    {
        $query->where('status', ChallengeStatus::Active);
    }

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'period_type' => PeriodType::class,
            'custom_period_days' => 'integer',
            'starts_at' => 'datetime',
            'total_periods' => 'integer',
            'visibility' => ChallengeVisibility::class,
            'proof_type' => ProofType::class,
            'proof_is_public' => 'boolean',
            'default_freezes' => 'integer',
            'status' => ChallengeStatus::class,
            'announced_at' => 'datetime',
        ];
    }
}
