<?php

use App\Enums\SettingKey;
use App\Exceptions\InvalidInitDataException;
use App\Services\Settings;
use App\Services\Telegram\InitDataSecretKey;
use App\Services\Telegram\InitDataVerifier;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Carbon;

uses(RefreshDatabase::class);

/*
 * The Mini App's signing chain, pinned against a value computed **outside PHP**.
 *
 * This file exists because the rest of the suite could not have caught the bug
 * that took the Mini App down in production. `InitDataVerifier` derived the
 * signing key with `hash_hmac('sha256', $token, 'WebAppData')` — the 64-character
 * hex rendering, where Telegram means the 32 raw bytes. Every fixture derived it
 * the same way, so app and tests agreed with each other perfectly while both
 * disagreed with Telegram, and the result was that a suite of 1800 tests was
 * green while the server refused **every** real user with "The initData hash does
 * not match its contents."
 *
 * A test that builds its expectation from the code under test can only ever
 * confirm that the code is self-consistent. So the expectations below are
 * literals, generated by `hmac`/`hashlib` in Python and pasted in, and the test
 * never derives them. To re-derive (only if the fixture's shared defaults ever
 * change), run:
 *
 *     python3 - <<'PY'
 *     import hmac, hashlib
 *     from urllib.parse import urlencode
 *     token = b"123456:TEST-TOKEN"
 *     fields = {
 *         "auth_date": "1700000000",
 *         "query_id": "AAF1q2W4vQ5x8z0b3C6d9E2f",
 *         "user": '{"id":7770005,"first_name":"Sara","last_name":"Ahmadi",'
 *                 '"username":"sarahmad","language_code":"en"}',
 *     }
 *     fields = dict(sorted(fields.items()))
 *     check = "\n".join(f"{k}={fields[k]}" for k in fields)
 *     raw = hmac.new(b"WebAppData", token, hashlib.sha256).digest()   # RAW, not .hexdigest()
 *     good = hmac.new(raw, check.encode(), hashlib.sha256).hexdigest()
 *     bad  = hmac.new(raw.hex().encode(), check.encode(), hashlib.sha256).hexdigest()
 *     print(raw.hex())          # 97b85f35…  — the key asserted below
 *     print(urlencode({**fields, "hash": good}))
 *     print(urlencode({**fields, "hash": bad}))
 *     PY
 *
 * `auth_date` is 2023-11-14, so the tests travel the clock back to it rather
 * than disabling the freshness window: the vector then exercises `assertFresh`
 * for real instead of stepping around it.
 */

const VECTOR_AUTH_DATE = 1_700_000_000;

/**
 * Signed with the raw digest — what Telegram actually sends.
 */
const GOLDEN_INIT_DATA = 'auth_date=1700000000&query_id=AAF1q2W4vQ5x8z0b3C6d9E2f&user=%7B%22id%22%3A7770005'
    .'%2C%22first_name%22%3A%22Sara%22%2C%22last_name%22%3A%22Ahmadi%22%2C%22username%22%3A%22sarahmad%22'
    .'%2C%22language_code%22%3A%22en%22%7D'
    .'&hash=07917198a500cb59858078c3ac565033ecdb01bdf6d650746e62b7a2fd3efd0a';

/**
 * The same fields signed with the hex string as the key — what this codebase sent
 * itself for months.
 */
const HEX_KEYED_INIT_DATA = 'auth_date=1700000000&query_id=AAF1q2W4vQ5x8z0b3C6d9E2f&user=%7B%22id%22%3A7770005'
    .'%2C%22first_name%22%3A%22Sara%22%2C%22last_name%22%3A%22Ahmadi%22%2C%22username%22%3A%22sarahmad%22'
    .'%2C%22language_code%22%3A%22en%22%7D'
    .'&hash=f626b72ea1c58b8619be57392f90fbf1e617de595bf8f0e40594e7583bb28269';

beforeEach(function () {
    config(['services.telegram.bot_token' => '123456:TEST-TOKEN']);

    // Frozen at the vector's own auth_date, so the window is the real one
    // (3600s) and this payload is genuinely fresh rather than exempted.
    test()->travelTo(Carbon::createFromTimestamp(VECTOR_AUTH_DATE));

    $this->verifier = app(InitDataVerifier::class);
});

it('verifies a payload signed by an implementation outside this codebase', function () {
    $verified = $this->verifier->verify(GOLDEN_INIT_DATA);

    expect($verified->user['id'])->toBe(7_770_005)
        ->and($verified->user['first_name'])->toBe('Sara')

        // `auth_date` and `query_id` survive into `fields`; `user` and `hash`
        // do not, because they are read out rather than passed along.
        ->and($verified->fields)->toHaveKey('query_id')
        ->and($verified->fields)->not->toHaveKey('user')
        ->and($verified->fields)->not->toHaveKey('hash');
});

it('rejects a payload signed with the hex rendering of the key', function () {
    // Not a security control — nobody without the bot token can produce this
    // either. It is here so that "accept both keys" cannot pass as a fix. That
    // band-aid would restore production, satisfy the positive vector, and leave
    // the derivation wrong in a way nothing else in this suite notices.
    expect(fn () => $this->verifier->verify(HEX_KEYED_INIT_DATA))
        ->toThrow(InvalidInitDataException::class);
});

it('derives the key Telegram specifies, and not its hex rendering', function () {
    // The primitive itself, asserted directly: 32 raw bytes, not 64 hex
    // characters. A length assertion is crude but it is the exact distinction
    // that broke production, and it fails the instant someone reaches for
    // `bin2hex` or drops the binary flag.
    $key = InitDataSecretKey::derive('123456:TEST-TOKEN');

    expect(strlen($key))->toBe(32)
        ->and(bin2hex($key))->toBe('97b85f353212ba6fa887c83713d6be865df1a84f004a490d2f0c564f57ec4513');
});

it('keeps the fixtures signing the committed vector byte for byte', function () {
    // The other half of breaking the circularity. The fixtures may use the same
    // primitive as production — that is what stops them drifting into a *new*
    // shared-but-wrong belief — but this pins their output to a literal they
    // cannot influence. Change `InitDataSecretKey`, or the encoding in the
    // fixture, and this fails rather than quietly re-signing everything.
    expect(initData(authDate: VECTOR_AUTH_DATE))->toBe(GOLDEN_INIT_DATA);
});

it('refuses a vector whose auth_date has aged out', function () {
    // Guards the guard: proves the freshness check in the tests above is doing
    // something, so a future `travelTo` removal fails with a message about
    // staleness rather than looking like a hash regression.
    test()->travelTo(Carbon::createFromTimestamp(VECTOR_AUTH_DATE + 3601));

    expect(fn () => $this->verifier->verify(GOLDEN_INIT_DATA))
        ->toThrow(InvalidInitDataException::class);

    // And the window really is the configured one, not a frozen clock.
    app(Settings::class)->set(SettingKey::InitDataMaxAgeSeconds, 7200);

    expect($this->verifier->verify(GOLDEN_INIT_DATA)->user['id'])->toBe(7_770_005);
});
