<?php

namespace App\Enums;

use App\Enums\Concerns\HasTranslatedLabel;
use App\Enums\Contracts\HasTranslatedLabel as HasTranslatedLabelContract;

/**
 * What a participant must do to prove a period's check-in.
 *
 * Chosen once by the creator, for the whole challenge.
 */
enum ProofType: string implements HasTranslatedLabelContract
{
    use HasTranslatedLabel;

    /**
     * One tap. Auto-approved.
     */
    case Button = 'button';

    /**
     * The system generates a phrase the participant must type back. Generated
     * per participant *per period*, so participants cannot paste it to each
     * other and defeat the mechanic. Auto-approved on normalised exact match.
     */
    case TextAutogen = 'text_autogen';

    /**
     * The participant uploads a photo and the creator approves or rejects it.
     */
    case ImageApproval = 'image_approval';

    /**
     * A voice message instead of a photo, reviewed the same way: creator
     * approves or rejects. Structurally identical to `image_approval` — only
     * the media kind differs, and with it a duration cap.
     */
    case VoiceApproval = 'voice_approval';

    /**
     * A video message, reviewed the same way again. Video is the heaviest
     * thing a participant can be asked to submit, so its duration and size are
     * capped at the challenge level and pruned on a retention window.
     */
    case VideoApproval = 'video_approval';

    /**
     * The proof types whose submission carries media for a human to look at.
     *
     * Voice and video join image here rather than growing their own parallel
     * switches: every rule that follows — review, reversal, public sharing,
     * retention — is the same rule about the same shape of submission.
     */
    public function isMediaApproval(): bool
    {
        return in_array($this, [self::ImageApproval, self::VoiceApproval, self::VideoApproval], true);
    }

    /**
     * Whether a submission is accepted without a human looking at it.
     */
    public function isAutoApproved(): bool
    {
        return ! $this->isMediaApproval();
    }

    /**
     * Whether the creator has to review submissions.
     */
    public function requiresReview(): bool
    {
        return ! $this->isAutoApproved();
    }

    /**
     * Whether the creator may make other participants' proofs visible.
     *
     * Only media proofs: a button tap has nothing to show, and publishing an
     * autogenerated phrase would hand every other participant the answer. A
     * voice note or a video shows exactly what a photo does, so they share the
     * gate. Sharing is opt-in even here — see `Challenge::$proof_is_public`.
     */
    public function supportsPublicProof(): bool
    {
        return $this->isMediaApproval();
    }

    /**
     * Whether a submission carries a phrase the participant typed.
     */
    public function expectsText(): bool
    {
        return $this === self::TextAutogen;
    }

    /**
     * Whether a submission carries an uploaded file.
     */
    public function expectsFile(): bool
    {
        return $this->isMediaApproval();
    }

    /**
     * Whether a submission carries media with a duration, and therefore a
     * challenge-level cap on it: a recording can run on where a photo cannot.
     *
     * This is what makes `proof_media_max_seconds` required — see
     * `CreateChallenge::assertMediaCaps()`.
     */
    public function expectsDuration(): bool
    {
        return in_array($this, [self::VoiceApproval, self::VideoApproval], true);
    }
}
