<?php

namespace App\Enums;

use App\Enums\Concerns\HasTranslatedLabel;
use App\Enums\Contracts\HasTranslatedLabel as HasTranslatedLabelContract;

/**
 * What a participant must do to prove a period's check-in.
 *
 * Chosen once by the creator, for the whole challenge.
 */
enum ProofType: string implements HasTranslatedLabelContract
{
    use HasTranslatedLabel;

    /**
     * One tap. Auto-approved.
     */
    case Button = 'button';

    /**
     * The system generates a phrase the participant must type back. Generated
     * per participant *per period*, so participants cannot paste it to each
     * other and defeat the mechanic. Auto-approved on normalised exact match.
     */
    case TextAutogen = 'text_autogen';

    /**
     * The participant uploads a photo and the creator approves or rejects it.
     */
    case ImageApproval = 'image_approval';

    /**
     * Whether a submission is accepted without a human looking at it.
     */
    public function isAutoApproved(): bool
    {
        return $this !== self::ImageApproval;
    }

    /**
     * Whether the creator has to review submissions.
     */
    public function requiresReview(): bool
    {
        return ! $this->isAutoApproved();
    }

    /**
     * Whether the creator may make other participants' proofs visible.
     *
     * Only image proofs: a button tap has nothing to show, and publishing an
     * autogenerated phrase would hand every other participant the answer.
     * Sharing is opt-in even here — see `Challenge::$proof_is_public`.
     */
    public function supportsPublicProof(): bool
    {
        return $this === self::ImageApproval;
    }

    /**
     * Whether a submission carries a phrase the participant typed.
     */
    public function expectsText(): bool
    {
        return $this === self::TextAutogen;
    }

    /**
     * Whether a submission carries an uploaded file.
     */
    public function expectsFile(): bool
    {
        return $this === self::ImageApproval;
    }
}
